version: '3'
services:
  front:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd front && yarn start'
    ports:
      - 8000:3000
    tty: true